name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Installing Dependencies
      run: |
        sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update
        sudo apt-get install xvfb; sudo apt-get install libgtk-3-dev libxdo-dev openbox
    
    - uses: actions/checkout@v2
    - name: Cache Cargo registry
      uses: actions/cache@v2
      env:
        cache-name: cache-cargo-registry
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-stable-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-stable-cargo-registry-
    - name: Cache Cargo index
      uses: actions/cache@v2
      env:
        cache-name: cache-cargo-index
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-stable-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-stable-cargo-index-
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
        DISPLAY: :99
      run: |
        Xvfb $DISPLAY &
        sleep 3
        openbox &
        cargo test --verbose -- --test-threads=1
