name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing Dependencies
      run: sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list; sudo apt-get update; sudo apt-get install xvfb; sudo apt-get install libgtk-3-dev libxdo-dev openbox;
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
        DISPLAY: :99
      run: |
        Xvfb $DISPLAY &
        sleep 3
        openbox &
        cargo test --verbose -- --test-threads=1
